version: '3.7'

# Networks
networks:
  # Internal network
  internal:
    driver: bridge
  reverse-proxy:
    external:
      name: reverse-proxy

volumes:
  guicommerce-mysql_data:
    driver: local

# Services
services:

  # Nginx
  guicommerce-nginx:
    image: webdevops/php-nginx-dev:8.1
    container_name: guicommerce-nginx
    restart: always
    networks:
      - internal
      - reverse-proxy
    working_dir: /var/www
    volumes:
      - .:/var/www
    environment:
      - WEB_DOCUMENT_ROOT=/var/www/public
      - WEB_DOCUMENT_INDEX=index.php
      - VIRTUAL_HOST=${DOCKER_DOMAIN}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${DOCKER_DOMAIN}
      - LETSENCRYPT_EMAIL=certificate@devi.tools

  guicommerce-mysql:
    image: mysql:5.7
    container_name: guicommerce-mysql
    restart: always
    networks:
      - internal
    volumes:
      - .:/var/www
      - guicommerce-mysql_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
