name: deploy

on: push

jobs:
  deploy:
    strategy:
      matrix:
        node-version: [12.x] # Only run the 12.x build

    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: git checkout master
      - run: git config --global user.email "ci@devi.tools"
      - run: git config --global user.name "CI"

      # go to artifacts project, create a new git repository and add all files
      - name: Configure repo
        run: |
          rm -rf .git
          git init
          git add .
          git commit --quiet -m "[deploy] $(date)"

      # configure ssh
      - name: Configure SSH
        run: |
          eval $(ssh-agent -s)
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo -e "${{ secrets.DEPLOY_SERVER_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa
          echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config

      # setup and execute deploy
      - name: Run push to sever
        run: |
          cd artifacts
          echo "Add host 165.22.182.175"
          echo -e "165.22.182.175" > ~/.ssh/known_hosts
          echo "chmod on ~/.ssh/known_hosts"
          chmod 644 ~/.ssh/known_hosts
          echo "Deploy 'master' (ssh://heimdall@165.22.182.175:22/projects/guicommerce.devi.tools/repo)"
          git remote add production ssh://heimdall@165.22.182.175:22/projects/guicommerce.devi.tools/repo
          git push production master --force